<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" ignored="0" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="233174" started-at="2021-06-23T16:26:35 IST" finished-at="2021-06-23T16:30:28 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="233174" started-at="2021-06-23T16:26:35 IST" finished-at="2021-06-23T16:30:28 IST">
      <class name="com.taxilla.suitea.InboundTest">
        <test-method status="PASS" signature="init()[pri:0, instance:com.taxilla.suitea.InboundTest@57e1b0c]" name="init" is-config="true" duration-ms="3718" started-at="2021-06-23T16:26:35 IST" finished-at="2021-06-23T16:26:38 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="FAIL" signature="inboundtest(java.util.Hashtable)[pri:0, instance:com.taxilla.suitea.InboundTest@57e1b0c]" name="inboundtest" duration-ms="222581" started-at="2021-06-23T16:26:41 IST" data-provider="getdata" finished-at="2021-06-23T16:30:24 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{TxtInputFileName=txt_asset.txt, AppName=InboundTestSuiteA, Runmode=Y, JsonInputFileName=json_asset.json, CsvInputFileName=csv_asset.csv, SecurityAnswer2=test, ExcelInputFileName=excel_asset.xlsx, XmlInputFileName=xml_asset.xml, SecurityAnswer1=test, CustomerName=dmartorg, Browser=firefox, CustomerPassword=Test@123}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.reflect.InvocationTargetException">
            <full-stacktrace>
              <![CDATA[java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.taxilla.Drivers.DriverScript.executeKeywords(DriverScript.java:133)
at com.taxilla.suitea.InboundTest.inboundtest(InboundTest.java:39)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.RuntimeException: Instance is not completed
at com.taxilla.keywords.AppKeyword.verifyInstanceStatus(AppKeyword.java:418)
... 34 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.reflect.InvocationTargetException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inboundtest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.taxilla.suitea.InboundTest@57e1b0c]" name="quit" is-config="true" duration-ms="2553" started-at="2021-06-23T16:30:24 IST" finished-at="2021-06-23T16:30:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="SKIP" signature="inboundtest(java.util.Hashtable)[pri:0, instance:com.taxilla.suitea.InboundTest@57e1b0c]" name="inboundtest" duration-ms="3" started-at="2021-06-23T16:30:27 IST" data-provider="getdata" finished-at="2021-06-23T16:30:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{TxtInputFileName=blank cell, AppName=blank cell, Runmode=N, JsonInputFileName=blank cell, CsvInputFileName=blank cell, SecurityAnswer2=blank cell, ExcelInputFileName=blank cell, XmlInputFileName=blank cell, SecurityAnswer1=P4, CustomerName=U2, Browser=firefox, CustomerPassword=P4}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode is set to NO
at com.taxilla.suitea.InboundTest.inboundtest(InboundTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inboundtest -->
        <test-method status="SKIP" signature="inboundtest(java.util.Hashtable)[pri:0, instance:com.taxilla.suitea.InboundTest@57e1b0c]" name="inboundtest" duration-ms="9" started-at="2021-06-23T16:30:27 IST" data-provider="getdata" finished-at="2021-06-23T16:30:27 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[{TxtInputFileName=blank cell, AppName=blank cell, Runmode=N, JsonInputFileName=blank cell, CsvInputFileName=blank cell, SecurityAnswer2=blank cell, ExcelInputFileName=blank cell, XmlInputFileName=blank cell, SecurityAnswer1=P3, CustomerName=U3, Browser=firefox, CustomerPassword=P3}]]>
              </value>
            </param>
          </params>
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Run mode is set to NO]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Run mode is set to NO
at com.taxilla.suitea.InboundTest.inboundtest(InboundTest.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inboundtest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.taxilla.suitea.InboundTest@57e1b0c]" name="quit" is-config="true" duration-ms="0" started-at="2021-06-23T16:30:27 IST" finished-at="2021-06-23T16:30:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.taxilla.suitea.InboundTest@57e1b0c]" name="quit" is-config="true" duration-ms="0" started-at="2021-06-23T16:30:27 IST" finished-at="2021-06-23T16:30:27 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.taxilla.suitea.InboundTest@57e1b0c]" name="afterTest" is-config="true" duration-ms="1198" started-at="2021-06-23T16:30:27 IST" finished-at="2021-06-23T16:30:28 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.taxilla.suitea.InboundTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
